image: node:8.12.0

cache:
  paths:
   - node_modules/

# before_script:
#   - npm install

before_script:
  - git remote set-url origin https://yagee:${CI_PUSH_TOKEN}@gitlab.com/your-project.git
  - git config --global user.email 'general@ya.ru'
  - git config --global user.name 'yagee'

stages:
  - build
  - deploy

build:
  stage: build
  only:
   - master
  script:
   - node_modules/gulp/bin/gulp.js --gulpfile ./gulpfile.js build
   # - git checkout -B branch
   # - change files
   - git commit -m '[skip ci] commit from CI runner'
   - git push --follow-tags origin master
  artifacts:
    paths:
      - public/
      - docs/

pages:
  stage: deploy
  script:
    - echo 'Nothing to do...'
  artifacts:
    paths:
    - public/
    - docs/
  only:
    - master
