image: node:8.12.0

cache:
  paths:
   - node_modules/

# before_script:
#   - npm install

before_script:
  # https://gitlab.com/yagee/ci-test.git

stages:
  - github
  - build
  - deploy

github:
  stage: github
  only:
   - master
  script:
   - git remote set-url origin https://yagee:$CI_PUSH_TOKEN@gitlab.com/yagee/ci-test.git
   - git config --global user.email 'general@ya.ru'
   - git config --global user.name 'yagee'
   - node_modules/gulp/bin/gulp.js --gulpfile ./gulpfile.js build
   - git checkout -B master
   - git add .
   # - change files
   - git commit -m '[skip ci] commit from CI runner'
   - git remote show origin
   # - git push --follow-tags origin master
   - git push -u origin master

   # - git checkout -B branch
   # # - change files
   # - git add .
   # - git commit -m '[skip ci] commit from CI runner'
   # - git push origin branch

build:
  stage: build
  only:
   - master
  script:
   - node_modules/gulp/bin/gulp.js --gulpfile ./gulpfile.js build
   - rm -rf public
   - mkdir public
   - cp -a build/ public/
  artifacts:
    paths:
      - public/

pages:
  stage: deploy
  script:
    - echo 'Nothing to do...'
  artifacts:
    paths:
      - public/
  only:
    - master
